#' Parses the content of an error generated by parse
#' 
#' Makes sense of a \code{parse} error and structure the information
#' @export
#' @param err An error as generated by \code{parse} 
#' @param only.last Should only the last line of the error be outputed into the structure
#' @return A data.frame with the following columns : file, line, message and type
#' @author Romain Francois \email{francoisromain@@free.fr}
parseError <- function( err, only.last = TRUE ){
  msg <- strsplit( err, "\\\n" )[[1]]
  line.nb <- as.integer(msg %~|% "^[[:digit:]]" %!~|% "^[[:digit:]]+:[[:space:]]*$" %-~|% ":.*"  )
  if( only.last ){
		line.nb <- tail( line.nb, 1 )
	}
	msg.line <- paste(msg %!~|% "^[[:digit:]]+", collapse=" " ) %/~% " *: *"
  file <- msg.line[2]
  err.msg <- msg.line[3]
  data.frame( file = rep(file, length(line.nb)), 
    line = line.nb, 
    message = rep(err.msg, length(line.nb) ), 
    type = rep( "error", length(line.nb) ), 
		stringsAsFactors = FALSE )
}

