#' Parses the content of an error generated by parse
#' 
#' Makes sense of a \code{parse} error and structure the information
#' @export
#' @param err An error as generated by \code{parse} 
#' @return A data.frame with the following columns : file, line, message and type
#' @author Romain Francois \email{francoisromain@@free.fr}
parseError <- function( err ){
  msg <- err %/~% "\\\n"
  rx   <- "^.*?: (.*?):(.*?):(.*?):(.*)$"
  file <- sub( rx, "\\1", msg[1], perl = TRUE )
  line <- sub( rx, "\\2", msg[1], perl = TRUE )
  col  <- sub( rx, "\\3", msg[1], perl = TRUE )
  message <- sub( rx, "\\4", msg[1], perl = TRUE )
  
  data.frame( file = file, 
    line = line, message = message, 
    type = "error", stringsAsFactors = FALSE )
}

